/**
 * TensorFlow.js model loader and inference utility.
 *
 * Models live in public/models/<id>/
 *   model.json    — TFJS graph (generated by convert_to_tfjs.py)
 *   weights.bin   — weight shards (generated alongside model.json)
 *   labels.json   — class names ["A","B","C",...] (generated by convert_to_tfjs.py)
 *
 * Inference input:
 *   63 floats — 21 MediaPipe hand landmarks each as [x-wx, y-wy, z-wz]
 *   (wrist-relative, matches the training format in main.py)
 *
 * All models are cached in memory after first load.
 * Loading is async and safe to call multiple times — returns the cached instance.
 */

// Cache: { modelId: { model: tf.GraphModel, labels: string[] } }
const _cache = {}

/**
 * Load a TFJS model by id. Returns { model, labels }.
 * Throws if the files aren't found (wrong path or not converted yet).
 */
export async function loadTFJSModel(modelId) {
  if (_cache[modelId]) return _cache[modelId]

  // TF.js is loaded as a classic <script> in index.html (window.tf)
  if (!window.tf) throw new Error('TensorFlow.js not loaded. Check index.html.')

  const base = `/models/${modelId}`

  const [model, labelsRes] = await Promise.all([
    window.tf.loadLayersModel(`${base}/model.json`),
    fetch(`${base}/labels.json`),
  ])

  if (!labelsRes.ok) throw new Error(`labels.json not found for model "${modelId}"`)
  const labels = await labelsRes.json()

  _cache[modelId] = { model, labels }
  return _cache[modelId]
}

/**
 * Run inference on 21 hand landmarks from MediaPipe.
 *
 * @param {Array} landmarks  - results.multiHandLandmarks[0] from MediaPipe
 * @param {string} modelId   - e.g. 'fsl'
 * @param {number} threshold - minimum confidence to return a letter (default 0.75)
 * @returns {{ letter: string, confidence: number }}
 */
export async function predictFromLandmarks(landmarks, modelId, threshold = 0.75) {
  try {
    const { model, labels } = await loadTFJSModel(modelId)

    // Wrist-relative normalisation — identical to backend main.py
    const wrist = landmarks[0]
    const features = []
    for (const lm of landmarks) {
      features.push(lm.x - wrist.x, lm.y - wrist.y, lm.z - wrist.z)
    }

    // Shape: [1, 63]
    const input  = window.tf.tensor2d([features], [1, 63])
    const output = model.predict(input)
    const probs  = await output.data()

    // Clean up tensors immediately to avoid memory leak
    input.dispose()
    output.dispose()

    const maxIdx    = probs.indexOf(Math.max(...probs))
    const confidence = probs[maxIdx]

    if (confidence < threshold) return { letter: 'None', confidence: +confidence.toFixed(3) }

    return {
      letter:     labels[maxIdx] ?? 'None',
      confidence: +confidence.toFixed(3),
    }
  } catch (e) {
    console.error('TFJS predict error:', e)
    return { letter: 'None', confidence: 0 }
  }
}
